### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by pactishka** [oleksandrblazhko/ai-214-sokolov#12]
Завдання 1:
| Потреба                     | доступність | зрозумілість | цінність    | актуальність |
| -----------                 | ----------- | -----------  | ----------- | -----------  |
| отримання даних             | -           | Незрозуміло  | -           | -            |

Доступність:  Отримання даних є доступною потребою , наприклад такі як Google , Wikipedia , або будь-який інший спосіб отримання даних в інтернеті.

Зрозумілість: Хоч і в інтернеті можливо знайти багато інформації та даних, але не кожна людина зрозуміє її , і що з нею робити.

Цінність: Дані в інтернеті здебільшого безплатні, тому кожна людина може нею скористатися без жодних проблем.

Актуальність: Отримання даних є актуальною потребою , бо завжди корисно дізнатися щось нове, або згадати щось старе.

Завдання 2:
Надати пояснення складання Online-замовлення, надання питань чи коментарів до скульптури та готування скульптури до відправки.

Feature: Складання Online-замовлення
As скульптор-цінитель
In order to зробити покупку в інтернет-магазині
I want to мати можлисть скласти онлайн-замовлення

Призначенням цього функціоналу є спрощення процесу оформлення замовлення для скульптор-цінителя. Користувач може швидко та легко вибрати товари, додати їх до кошика і зробити замовлення онлайн. Це надає можливість швидко досягти мети - придбати бажану скульптуру - без зайвих операцій та затрат часу.

Feature: Надання питань чи коментарів до скульптури
As a скульптор-цінитель
In order to спілкування з автором скульптури
I want to мати можливість надати питання чи коментарі

Ця функція створює можливість спілкування між скульптором-цінителем та користувачем, який цікавиться скульптурою. Користувач може задавати питання, висловлювати коментарі, і отримувати відповіді від автора. Це підвищує інтерактивність та залученість користувача, сприяючи досягненню мети спілкування з автором скульптури.

Feature: Готування скульптури до відправки
As a майстер скульптор
In order to вчасно та безпечно доставки скульптури клієнту
I want to мати можливість підготувати скульптуру до відправки

Ця функція допомагає майстру скульптору підготувати скульптуру до відправки клієнту швидко та безпечно. Вона включає в себе опції упаковки, маркування та обробки для транспортування. Результат роботи цієї функції допомагає користувачу отримати свою скульптуру в надійному стані, що сприяє досягненню його мети отримання товару вчасно та безпечно.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 4 бали
