### ISSUE TITLE
CW2

### ISSUE THREAD

**Issue by pactishka** [oleksandrblazhko/ai-214-sokolov#15]

**Comment by pactishka** [comment]
1 ЗАВДАННЯ

|   FR     | Опис функціональної вимоги|
|----------|---------------------------|
| FR1.2 | Коритувачу надається перелік скульптур |
| FR1.3 | Користувач надсилає технічні запитання офісному співробітнику |
| FR2.1 | Користувач робить замовлення скульптури |

1) FR1.2 - "атомарність"
Користувачу надається перелік скульптур, але цей перелік може змінюватися без попередження іноді, в залежності від розглядуваних факторів.

2) FR1.3 - "завершеність"
Користувач надсилає технічні запитання офісному співробітнику, але система не гарантує, що вони будуть збережені та відповідати всім потребам користувача.

3) FR2.2 - "безкоштовність реалізації"
Користувач робить замовлення скульптури та обговорює всі деталі та особливості з офісним співробітником перед підтвердженням замовлення.

2 ЗАВДАННЯ

Показник | Опис показника | Вага_i | STi | STi * Вага_i | 
-- | -- | -- | -- | -- | 
Т1 | Розподілена система | 2 | 3 | 6 | 
T13 | Спеціальні вимоги до навчання користувачів | 1 | 0 | 0 |

1. Показник технічної складності проекту "Розподілена система":

Обгрунтування визначення показника:

Розподілена система: Оцінка складності 3 з 5 (STi = 3) вказує на середню складність. Це свідчить про те, що архітектура розподіленої системи потребує серйозних зусиль для правильної організації та управління ресурсами.

Вага (вага_i): Вага 2 вказує на значущий вплив цього показника на загальну технічну складність проекту, оскільки розподілені системи можуть відігравати ключову роль у функціональності та ефективності продукту.

STi * Вага_i: Розрахунок STi * Вага_i дорівнює 6, що вказує на значний вплив архітектури розподіленої системи на загальну технічну складність проекту.

2. Показник технічної складності проекту "Спеціальні вимоги до навчання користувачів":

Обгрунтування визначення показника:

Спеціальні вимоги до навчання користувачів: Оцінка складності 0 з 5 (STi = 0) свідчить про відсутність або дуже низьку складність вимог до навчання користувачів.

Вага (вага_i): Вага 1 показує, що цей показник має менший вплив на загальну технічну складність проекту порівняно з іншими аспектами.

STi * Вага_i: Розрахунок STi * Вага_i дорівнює 0, вказуючи на дуже обмежений вплив спеціальних вимог до навчання користувачів на загальну технічну складність проекту. У цьому випадку, цей аспект не сприяє загальній складності проекту.

**Comment by oleksandrblazhko** [comment]
1) Коментар до рішення 1-го завдання:
"безкоштовніcть реалізації" порушується, якщо, наприклад, 
використовуються графічний інтерфейс
2) Коментар до рішення 2-го завдання:
треба було врахувати назви акторів, які будуть використовувати програмний продукт.

оцінка  = 2 бали
